# Generated by Django 4.1.3 on 2022-12-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://thumbs.dreamstime.com/b/pizza-rustic-italian-mozzarella-cheese-basil-leaves-35669930.jpg', max_length=500),
        ),
    ]
